---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  remote_user: sys-admin
#  gather_facts: false
  
# encrypted passwords, generated on a Linux box using: 
#For Old OS
# echo 'import crypt,getpass; print crypt.crypt(getpass.getpass(), "$6$YOURSALT")' | python -

# For Latest OS
# python3 -c 'import crypt,getpass;pw=getpass.getpass();print(crypt.crypt(pw) if (pw==getpass.getpass("Confirm: ")) else exit())'

  vars:
    root_pass: '$6$ATWdR/xP4x1.kEUA$V9RiCyqrI4dCudwzGDc3bOdqILzUbtD.WVItTQ1sjPPGyDG2HbzL4mb0T4ySAE8j4tpDoadx01K9DCopHom16/'  

  tasks:
    - name: Change root password
      user: 
        name: root 
        update_password: always 
        password: "{{root_pass}}"
