---
- hosts: all
  become: yes
  become_user: root
  become_method: su
  remote_user: admin

  tasks:
   - name: Use DNS 8.8.8.8 instead of 10.0.0.30
     replace:
      path: /etc/resolv.conf
      regexp: "10.0.0.30"
      replace: "8.8.8.8"

   - name: Use DNS 1.1.1.1 instead of 10.0.0.31
     replace:
      path: /etc/resolv.conf
      regexp: "10.0.0.31"
      replace: "1.1.1.1"

   - name: find change DNS
     shell: cat /etc/resolv.conf |grep nameserver
     register: command_output

   - name: Print Output
     debug:
      msg: "{{ command_output.stdout_lines | join('\n') }}"
