---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  remote_user: sys-admin

  tasks:
    - name: Remove Puppet Agent 
      yum:
        name: puppet-agent
        state: absent
