---
- hosts: all
  become: yes
  become_user: root
  become_method: su
  remote_user: admin

  tasks:
   - name: Copy SentinelOne to target server
     copy: src=../files/SentinelAgent_linux_v21_10_3_3.rpm dest=/home/admin/ force=no

   - name: Install SentinelOne package
     shell: rpm -ivh --nodigest SentinelAgent_linux_v21_10_3_3.rpm
     args:
      chdir: /home/admin

   - name: Assign token to SentinelOne Agent
     command: /opt/sentinelone/bin/sentinelctl management token set eyJ1cmwiOiAiaHR0cHM6Ly9m5ldCIsICJzaXRlX2tleSI6ICI5M2VmMjA4ZmNkNWRmZWIxIn0=

   - name: Start SentinelOne Agent
     command: /opt/sentinelone/bin/sentinelctl control start

   - name: Check SentinelOne UUID
     command: /opt/sentinelone/bin/sentinelctl management uuid get

## Verify YAML file.
ansible-playbook --syntax-check sentinelone-agent-install.yaml

## Apply ansible playbook
ansible-playbook -l prod -k -K sentinelone-agent-install.yaml

SSH password: here admin user password should be provide
BECOME password[defaults to SSH password]: here root user password should be provide

In above command: 
-k means admin user password
-K means root user password
