- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  remote_user: sys-admin

  tasks:
   - name: Restart & Enable Wazuh Agent Service
     systemd:
      state: restarted
      daemon_reload: yes
      enabled: yes  
      name: wazuh-agent

   - name: print current version
     shell: rpmquery wazuh-agent
     register: command_output

   - name: Print Output
     debug:
      msg: "{{ command_output.stdout_lines | join('\n') }}"
